// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKKmI2pOeqxC-rh74Qwdhf59wNZabMHt4',
    appId: '1:1007109397441:web:111ca00a8cc057e2186d40',
    messagingSenderId: '1007109397441',
    projectId: 'zclassic',
    authDomain: 'zclassic.firebaseapp.com',
    storageBucket: 'zclassic.appspot.com',
    measurementId: 'G-3B3RFV60WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsihQS3WHjzDR56gHrfqMo78MtD9o4CHI',
    appId: '1:1007109397441:android:169f0cb085cead34186d40',
    messagingSenderId: '1007109397441',
    projectId: 'zclassic',
    storageBucket: 'zclassic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7AN-aZ3eJjO85gX5Kk8ttG_WRBByWyHE',
    appId: '1:1007109397441:ios:c1de81f8ab92406b186d40',
    messagingSenderId: '1007109397441',
    projectId: 'zclassic',
    storageBucket: 'zclassic.appspot.com',
    iosClientId: '1007109397441-grnhebqo6g1tqhsf2b2mggpthau8p71p.apps.googleusercontent.com',
    iosBundleId: 'com.example.zclassic',
  );
}
